name: neumorphic
description: Neumorphic UI. Implementation of Neumorphism user interface consisting of sets of principles and widgets for the Flutter framework
version: 0.0.2+1
homepage: https://github.com/neumorphic/neumorphic

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
